#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <iostream>
#include <cmath>
#include <shader.h>
#include <cube.h>
#include <arcball.h>
#include <cstdlib>
#include "pyramid.h"
#include "bucket.h"
#include "fighter_plane.h"
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
